version: '3'
 
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: admin
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql 
      - ./conf:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
    - db
  python:
    image: python:3.8-slim-buster
    container_name: python_db
    volumes:
      - ./python:/app
    command: python /app/main.py
    links:
      - db
    depends_on:
      - db
volumes:
  dbdata: