version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: admin
    ports:
      - "6033:3306"
    volumes:
      # - dbdata:/var/lib/mysql 
      - ./conf:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
    - mysql
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    depends_on:
      - mysql
  python:
    image: python:3.8-slim-buster
    container_name: python_db
    volumes:
      - ./python:/app
    command: python /app/main.py
    links:
      - mysql
    depends_on:
      - mysql
volumes:
  grafana-data:
  mysql-data:

