version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgresadmin
      POSTGRES_DB: prueba

    volumes:
      # copy the sql script to create tables
      - ./sql:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgresadmin@postgres:5432/prueba?sslmode=disable"
    links:
      - postgres
      - prometheus
